POWER_TOGGLE_INIT_SLEEP = 0.01
POWER_TOGGLE_SLEEP = 1

INIT_SLEEP = 0.1
AFTER_SLEEP = 0.05

POWER_IN = 4
POWER_OUT = 17

INPUT_IN = 18
INPUT_OUT = 23

VOLUME_UP_IN = 24
VOLUME_UP_OUT = 25

VOLUME_DOWN_IN = 12
VOLUME_DOWN_OUT = 16

MENU_IN = 27
MENU_OUT = 22

_3D_IN = 5
_3D_OUT = 6

inputs = (POWER_IN, INPUT_IN, VOLUME_UP_IN, VOLUME_DOWN_IN, MENU_IN, _3D_IN)
outputs = (POWER_OUT, INPUT_OUT, VOLUME_UP_OUT, VOLUME_DOWN_OUT, MENU_OUT, _3D_OUT)

WEBSOCKET_PING_INTERVAL_SECONDS = 60*9 # 9 minutes